/**
 * Offline audit-bundle verifier tests.
 *
 * Shares fixtures with the Python SDK — regenerated by
 * `contract/tools/gen_audit_bundles.py`. Test names mirror the Python
 * suite so behavioural drift between the two SDKs is easy to spot.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  canonicalJSON,
  signedBytesFor,
  verifyAuditBundle,
  verifyBundle,
  type AuditBundle,
  type VerifyKey,
} from "../src/auditBundle.js";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const FIXTURES = resolve(HERE, "..", "..", "contract", "vectors", "audit-bundles");
const PUBLIC_PEM = readFileSync(resolve(FIXTURES, "signing-key.pub.pem"), "utf8");

function bundlePath(name: string): string {
  return resolve(FIXTURES, name);
}

function loadBundle(name: string): AuditBundle {
  const raw = JSON.parse(readFileSync(bundlePath(name), "utf8"));
  return raw.bundle ?? raw;
}

describe("canonicalJSON", () => {
  it("sorts object keys at every depth", () => {
    expect(canonicalJSON({ b: 1, a: { z: 2, y: 3 } })).toBe('{"a":{"y":3,"z":2},"b":1}');
  });

  it("normalizes null, undefined, and non-finite numbers to null", () => {
    expect(canonicalJSON(null)).toBe("null");
    expect(canonicalJSON(undefined)).toBe("null");
    expect(canonicalJSON(Number.NaN)).toBe("null");
    expect(canonicalJSON(Number.POSITIVE_INFINITY)).toBe("null");
  });

  it("preserves array order", () => {
    expect(canonicalJSON([3, 1, 2])).toBe("[3,1,2]");
  });

  it("uses standard JSON string escapes", () => {
    expect(canonicalJSON('hello "world"\n')).toBe('"hello \\"world\\"\\n"');
  });
});

describe("verifyBundle against shared fixtures", () => {
  it("valid bundle → every check passes", async () => {
    const r = await verifyBundle(bundlePath("valid.json"), { publicKeysPem: [PUBLIC_PEM] });
    expect(r.verified).toBe(true);
    expect(r.chainIntegrityOk).toBe(true);
    expect(r.signatureValid).toBe(true);
    expect(r.headHashMatches).toBe(true);
    expect(r.tamperedEventIds).toEqual([]);
    expect(r.reason).toBeUndefined();
    expect(r.matchedKeyId).toBe("pem_0");
  });

  it("tampered event → hash mismatch surfaces the event id", async () => {
    const r = await verifyBundle(bundlePath("tampered-event.json"), { publicKeysPem: [PUBLIC_PEM] });
    expect(r.verified).toBe(false);
    expect(r.chainIntegrityOk).toBe(false);
    expect(r.tamperedEventIds).toContain("evt-2");
    expect(r.signatureValid).toBe(false);
  });

  it("flipped signature bit → signatureValid false, chain still intact", async () => {
    const r = await verifyBundle(bundlePath("bad-signature.json"), { publicKeysPem: [PUBLIC_PEM] });
    expect(r.chainIntegrityOk).toBe(true);
    expect(r.signatureValid).toBe(false);
    expect(r.reason).toBeDefined();
  });

  it("wrong key → signature does not verify", async () => {
    const r = await verifyBundle(bundlePath("wrong-key.json"), { publicKeysPem: [PUBLIC_PEM] });
    expect(r.signatureValid).toBe(false);
    expect(r.chainIntegrityOk).toBe(true);
    expect(r.reason).toContain("1 configured");
  });

  it("broken chain → integrity fails (signature priority in `reason`)", async () => {
    const r = await verifyBundle(bundlePath("broken-chain.json"), { publicKeysPem: [PUBLIC_PEM] });
    expect(r.chainIntegrityOk).toBe(false);
    expect(r.signatureValid).toBe(false);
    expect(r.reason).toBeDefined();
  });

  it("no keys supplied → signature never verifies, chain still runs", async () => {
    const r = await verifyBundle(bundlePath("valid.json"));
    expect(r.chainIntegrityOk).toBe(true);
    expect(r.signatureValid).toBe(false);
    expect(r.reason).toContain("no signing keys");
  });

  it("malformed PEM is skipped, real PEM still verifies", async () => {
    const r = await verifyBundle(bundlePath("valid.json"), {
      publicKeysPem: [
        "-----BEGIN PUBLIC KEY-----\nnope\n-----END PUBLIC KEY-----",
        PUBLIC_PEM,
      ],
    });
    expect(r.signatureValid).toBe(true);
  });
});

describe("verifyAuditBundle low-level", () => {
  it("accepts an already-parsed bundle object", async () => {
    const bundle = loadBundle("valid.json");
    // Reuse the PEM-imported key and tag it with the bundle's hint
    // to exercise the rotation-first-try path.
    const keys = await keysFromPem(PUBLIC_PEM, "test-key");
    const r = await verifyAuditBundle(bundle, keys);
    expect(r.signatureValid).toBe(true);
    expect(r.matchedKeyId).toBe("test-key");
  });

  it("signedBytesFor emits the key order v1-audit signs", () => {
    const bundle = loadBundle("valid.json");
    const envelope = new TextDecoder().decode(signedBytesFor(bundle));
    expect(envelope.startsWith('{"export_id":')).toBe(true);
    expect(envelope.indexOf('"export_id":')).toBeLessThan(envelope.indexOf('"events":'));
  });

  it("bundle without signature → signatureValid false, reason present", async () => {
    const bundle = { ...loadBundle("valid.json") };
    delete bundle.signature;
    const keys = await keysFromPem(PUBLIC_PEM, "k");
    const r = await verifyAuditBundle(bundle, keys);
    expect(r.signatureValid).toBe(false);
    expect(r.reason).toContain("no signature");
  });
});

async function keysFromPem(pem: string, keyId: string): Promise<VerifyKey[]> {
  const b64 = pem
    .replace(/-----BEGIN PUBLIC KEY-----/, "")
    .replace(/-----END PUBLIC KEY-----/, "")
    .replace(/\s+/g, "");
  const bytes = Uint8Array.from(Buffer.from(b64, "base64"));
  const { webcrypto } = await import("node:crypto");
  const publicKey = await webcrypto.subtle.importKey(
    "spki",
    bytes,
    { name: "Ed25519" },
    false,
    ["verify"],
  );
  return [{ keyId, publicKey }];
}
