"""Offline audit-bundle verifier tests.

The fixtures live in ``contract/vectors/audit-bundles/`` and are shared
with the TypeScript SDK — regenerated by
``contract/tools/gen_audit_bundles.py``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from atlasent import BundleVerificationResult
from atlasent.audit_bundle import (
    canonical_json,
    signed_bytes_for,
    verify_audit_bundle,
    verify_bundle,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURES = REPO_ROOT / "contract" / "vectors" / "audit-bundles"
PUBLIC_PEM = (FIXTURES / "signing-key.pub.pem").read_text() if FIXTURES.exists() else ""

try:
    from atlasent.audit_bundle import _require_crypto

    _require_crypto()
    _CRYPTO_OK = True
except BaseException:
    _CRYPTO_OK = False

pytestmark = pytest.mark.skipif(
    not FIXTURES.exists() or not _CRYPTO_OK,
    reason=(
        "contract/vectors/audit-bundles/ not present, "
        "or cryptography package unavailable/broken"
    ),
)


def _load(name: str) -> dict:
    data = json.loads((FIXTURES / name).read_text())
    return data["bundle"] if isinstance(data, dict) and "bundle" in data else data


# ─── canonical_json ──────────────────────────────────────────────────


def test_canonical_json_sorts_keys_recursively() -> None:
    assert (
        canonical_json({"b": 1, "a": {"z": 2, "y": 3}}) == '{"a":{"y":3,"z":2},"b":1}'
    )


def test_canonical_json_normalizes_none_and_nonfinite() -> None:
    assert canonical_json(None) == "null"
    assert canonical_json(float("nan")) == "null"
    assert canonical_json(float("inf")) == "null"


def test_canonical_json_preserves_array_order() -> None:
    assert canonical_json([3, 1, 2]) == "[3,1,2]"


def test_canonical_json_string_escapes_match_json_dumps() -> None:
    # Backtick-safe: must match `JSON.stringify("…")` output for
    # identical bytes under signing.
    s = 'hello "world"\n'
    assert canonical_json(s) == '"hello \\"world\\"\\n"'


# ─── verify_bundle against shared fixtures ───────────────────────────


def test_valid_bundle_all_checks_pass() -> None:
    r = verify_bundle(FIXTURES / "valid.json", public_keys_pem=[PUBLIC_PEM])
    assert r.verified
    assert r.chain_integrity_ok
    assert r.signature_valid
    assert r.head_hash_matches
    assert r.tampered_event_ids == []
    assert r.reason is None
    assert r.matched_key_id == "pem_0"


def test_tampered_event_surfaces_event_id() -> None:
    r = verify_bundle(FIXTURES / "tampered-event.json", public_keys_pem=[PUBLIC_PEM])
    assert not r.verified
    assert not r.chain_integrity_ok
    assert "evt-2" in r.tampered_event_ids
    # Signature over the ORIGINAL envelope doesn't match the mutated bytes.
    assert not r.signature_valid


def test_bad_signature_flagged() -> None:
    r = verify_bundle(FIXTURES / "bad-signature.json", public_keys_pem=[PUBLIC_PEM])
    assert not r.verified
    assert r.chain_integrity_ok  # chain is untouched
    assert not r.signature_valid
    assert r.reason is not None


def test_wrong_key_does_not_verify() -> None:
    r = verify_bundle(FIXTURES / "wrong-key.json", public_keys_pem=[PUBLIC_PEM])
    assert not r.signature_valid
    assert r.chain_integrity_ok
    assert r.reason is not None and "1" in r.reason  # "1 configured public key(s)"


def test_broken_chain_fails_integrity() -> None:
    # Mutating previous_hash also changes the envelope bytes, so both
    # the chain check and the signature check fail. Signature reason
    # takes priority when both trip — matches the backend verifier.
    r = verify_bundle(FIXTURES / "broken-chain.json", public_keys_pem=[PUBLIC_PEM])
    assert not r.chain_integrity_ok
    assert not r.signature_valid
    assert r.reason is not None


def test_missing_public_keys_never_verifies_signature() -> None:
    r = verify_bundle(FIXTURES / "valid.json")
    assert r.chain_integrity_ok
    assert not r.signature_valid
    assert r.reason is not None and "no signing keys" in r.reason


def test_malformed_pem_is_skipped_not_fatal() -> None:
    # First key is garbage → dropped; second is the real one → verifies.
    r = verify_bundle(
        FIXTURES / "valid.json",
        public_keys_pem=[
            "-----BEGIN PUBLIC KEY-----\nnope\n-----END PUBLIC KEY-----",
            PUBLIC_PEM,
        ],
    )
    assert r.signature_valid


# ─── verify_audit_bundle low-level ───────────────────────────────────


def test_verify_audit_bundle_accepts_parsed_dict() -> None:
    bundle = _load("valid.json")
    from cryptography.hazmat.primitives import serialization

    from atlasent.audit_bundle import VerifyKey

    key = serialization.load_pem_public_key(PUBLIC_PEM.encode())
    r = verify_audit_bundle(bundle, [VerifyKey(key_id="test-key", public_key=key)])  # type: ignore[arg-type]
    assert r.signature_valid
    assert r.matched_key_id == "test-key"  # rotation hint matched


def test_signed_bytes_for_matches_v8_stringify_order() -> None:
    bundle = _load("valid.json")
    envelope = signed_bytes_for(bundle).decode()
    # export_id must come first, events last — this is the order
    # v1-audit/index.ts::handleExport writes, and a byte mismatch here
    # breaks offline verification.
    assert envelope.startswith('{"export_id":')
    assert '"events":' in envelope
    assert envelope.index('"export_id":') < envelope.index('"events":')


def test_bundle_without_signature_has_reason() -> None:
    from cryptography.hazmat.primitives import serialization

    from atlasent.audit_bundle import VerifyKey

    bundle = _load("valid.json")
    bundle = {**bundle}
    bundle.pop("signature")
    key = serialization.load_pem_public_key(PUBLIC_PEM.encode())
    r = verify_audit_bundle(bundle, [VerifyKey(key_id="k", public_key=key)])  # type: ignore[arg-type]
    assert not r.signature_valid
    assert r.reason is not None and "no signature" in r.reason


def test_result_has_verified_shortcut() -> None:
    r = BundleVerificationResult(
        chain_integrity_ok=True, signature_valid=True, head_hash_matches=True
    )
    assert r.verified
    r2 = BundleVerificationResult(
        chain_integrity_ok=True, signature_valid=False, head_hash_matches=True
    )
    assert not r2.verified
